function summary = summarizeWaterTankMetrics(metrics, evalCfg)

failureRate = mean(metrics.Failed);
numFailures = sum(metrics.Failed);

meanFinalMAE = mean(metrics.FinalMAE);
maxFinalMAE = max(metrics.FinalMAE);
p90FinalMAE = prctile(metrics.FinalMAE, 90);

meanIAE = mean(metrics.IAE);
maxIAE = max(metrics.IAE);

meanISE = mean(metrics.ISE);

validSettling = metrics.SettlingTime(~isnan(metrics.SettlingTime));
if isempty(validSettling)
    meanSettlingTime = NaN;
else
    meanSettlingTime = mean(validSettling);
end

meanUEnergy = mean(metrics.UEnergy);
meanDuEnergy = mean(metrics.DuEnergy);

if failureRate > 0
    J = evalCfg.Score.failureBasePenalty + ...
        evalCfg.Score.failureRateWeight * failureRate + ...
        evalCfg.Score.meanFinalMAEWeight * meanFinalMAE;
else
    J = ...
        evalCfg.Score.meanFinalMAEWeight * meanFinalMAE + ...
        evalCfg.Score.maxFinalMAEWeight  * maxFinalMAE + ...
        evalCfg.Score.meanIAEWeight      * meanIAE + ...
        evalCfg.Score.meanUEnergyWeight  * meanUEnergy + ...
        evalCfg.Score.meanDuEnergyWeight * meanDuEnergy;
end

score = -J;

summary = table( ...
    score, J, ...
    failureRate, numFailures, ...
    meanFinalMAE, maxFinalMAE, p90FinalMAE, ...
    meanIAE, maxIAE, meanISE, ...
    meanSettlingTime, ...
    meanUEnergy, meanDuEnergy, ...
    'VariableNames', [ ...
        "Score","Cost", ...
        "FailureRate","NumFailures", ...
        "MeanFinalMAE","MaxFinalMAE","P90FinalMAE", ...
        "MeanIAE","MaxIAE","MeanISE", ...
        "MeanSettlingTime", ...
        "MeanUEnergy","MeanDuEnergy"]);

end