function [statistic, scores, data] = waterTankTrainingEvaluator(agent, env, trainingInfo, evalCfg, stage, stageIndex)

result = evaluateWaterTankController( ...
    agent, env, evalCfg.TrainingCases, evalCfg, ...
    "ControllerName", "DDPG", ...
    "EvalSetName", "training_validation", ...
    "StageIndex", stageIndex, ...
    "StageName", stage.Name, ...
    "TrainingEpisode", trainingInfo.EpisodeIndex);

statistic = result.summary.Score;

% scores can be case-level scores. MATLAB stores this alongside the scalar
% statistic returned by the custom evaluator.
scores = -result.metrics.CaseCost;

data = result;

fprintf("\n[Eval] Stage %d | Episode %d | Score %.4f | FailureRate %.2f | meanFinalMAE %.4f | maxFinalMAE %.4f\n", ...
    stageIndex, ...
    trainingInfo.EpisodeIndex, ...
    result.summary.Score, ...
    result.summary.FailureRate, ...
    result.summary.MeanFinalMAE, ...
    result.summary.MaxFinalMAE);

end